version: '2'
services:
    alcoholrecommender-app:
        image: alcoholrecommender
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://alcoholrecommender-postgresql:5432/AlcoholRecommender
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    alcoholrecommender-postgresql:
        extends:
            file: postgresql.yml
            service: alcoholrecommender-postgresql
